hostname: database_server
rancher:
  bootstrap_docker:
    registry_mirror: https://qi1w8946.mirror.aliyuncs.com
  docker:
    registry_mirror: https://qi1w8946.mirror.aliyuncs.com
  system_docker:
    registry_mirror: https://qi1w8946.mirror.aliyuncs.com
  network:
    dns:
      nameservers:
        - 114.114.114.114
        - 115.115.115.115
    interfaces:
      eth0:
        address: 192.168.1.250/24
        gateway: 192.168.1.1
        mtu: 1500
        dhcp: false
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCzfp0i4GupwIvgh16BsdrY24DVwARTfTLV3oGQgDhSIaQuDbGJQ3Maj9OvSlMrJFNBAqXT2smK95gKmd6lmcODZ2CrmT+tODdyT5/eqZBItzrR89216AorgGxecHzsWeaiF1Gffj7+rB/ZNzDkX/AStOnAg68Eg+NrjCx7C8dnt2LLQkEh3pJBIlRNc6FOXbJeSy6Em/LgvMnQ8DERigDO/qSk+5a80qECbn3DB0/ZSw9Ipfaz8R75ItC0J+TIiB9DuSNI4SvhRyX8A2VqbWd1QJEH2Zx8m59IDdE03dpTTDVkrRWE6P/MeE1NKDbJqkTMX3itUEnSIUo0QSXqQpWP Administrator@PC-RecallCode
