#Hostname Config
hostname: Rancher
rancher:
        #Docker Config
        bootstrap_docker:
                registry_mirror: https://qi1w8946.mirror.aliyuncs.com
        docker: 
                registry_mirror: https://qi1w8946.mirror.aliyuncs.com
        system_docker:
                registry_mirror: https://qi1w8946.mirror.aliyuncs.com
        #Network Config
        network:
                interfaces:
                        eth0:
                                address: 192.168.1.250/24
                                gateway: 192.168.1.1
                                mtu: 1500
                                dhcp: false
#SSH Key Config
ssh_authorized_keys:
        ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCb6QRkh9axwoXA/IZkw1B3L083Uh9MKSGzoMGJVXHea12pKrL4TqGecAnVQaTGYgmaUCHFzXr3kj8xkKiNJnhBOqOeoLOvEm3XsGFkdwmZa1A/oNU+9+o/8JUB3Ds0OJQMD/QthTLYnJD2ib/94aAJ+9+FDd5zKFnhxTu9Iy1UBgHDplMXLYwzcK+5gaWidkkKWk7hZ9izZbAu1L2rKElySmSybxhtRI99Ta7wMJMpm5ufjKbUBclqEZ55Z33V7aBl7BkJcp4+elg6KC99WYVSkrG7DnFYQ8Ph030Jr9qp8bRmgfwK9nWu56NkkhXIsgvonWGIAo5NgUXtoJeXpVbv Administrator@PC-RecallCode
